language: node_js

node_js:
  - "4"

before_install:
  - npm install -g npm@latest
  - npm install -g gulp

install:
  - npm install --ignore-scripts

script:
  - npm test

deploy:
  # Deploy resources on master branch pushes.
  - provider: script
    skip_cleanup: true
    script: gulp publish
    on:
      branch: master

  # Deploy resources on a new release.
  - provider: script
    skip_cleanup: true
    script: gulp publish --for-real
    on:
      tags: true
      condition: "$TRAVIS_TAG = $(grep -m 1 version package.json | awk '{ print \"v\" $2 }' | sed 's/[\",]//g')"

  # Deploy the style guide on master branch pushes.
  - provider: heroku
    api_key:
      secure: "TbhP7ewja+SDtZnwpxLAuBCGr4s6RJStsGRP+tCzKd05BNt0y4frAwXYmVBZlgDc1XX0366SdeN3KIuPmHuj8GL5cP5ND51/xGIk8XoOPLIcqinwv1nTuZChAv2iyJSDMzGcsO64cNd38E2Kyiv5hpWtGbTviYI6k9I4efNGL7ZHO4VHStBNxZz4DMobe4dd3dLhEzabPJc5mr4XCCTR/4ffpVMcGYDSiqvPT7QMsMtvWn6u3eGSlMlYVFBMSlVV1n8gJBDVkU7e9Q7z7b3EevY+Ko/rSfJ686iohfH6hljMBZw8EORUBzk/aYZFwwUW3RNqX6CeGmgKhXcT+hJlBt4jC1faQ0Z+2grl2b8HdK0XBn6jWc3BmRvIxLZ7xkQVxXGez3X9QCkfRHYPWB2XaJ7xCbRAli9mfpTaRgZnLE6l2AaMONV0SaKwZU9tmA4ira8RWaEKHk8xl2/MyWzuEyJchcqndAaA2K7V8RM60QO1Mbx5j5qA8xcoI37t6o2ZOk4umBCkbtzOTNWwOt/YEn2OQDee+xIxwdsaryYnzvpcNKcVBj8ndbMNVmBUubIhT3y8CKhRpAiHllbhGTkVPSvqYvSFBA6Szq37Y3QLvo3zT0e+ESZlGlacE2wClHj942zAoGUUxVciS0K/WHlOG+fQbsFDJYtTRYiL7mABPpM="
    app: graze-pistachio
    on:
      branch: master

cache:
  directories:
    - node_modules/

env:
  global:
    - secure: ibaiBEya5jG6YvUbRNhItyrnMrOnyj5FosW7Z/dgrW0exVWg9NlG81xpTdQfLDHTmeTSjaImFYu64OOWiWHFYJc1uytasII+i8LxaFZN4+Ac+v0SSN+9Prw8DhszMYXqqw/fwcTSLPl/E5I5O/D6EPd8oSUe/pWQPUZmeOJOYfM7p93QNvVoGznMOjhwLbsmb+2v/dSQ09Rsa/Raj22dlizeI5PoAtDh8rAfvyMrlNc+2MJoWszHogc9eSxSHG7QCip0jttor97UkqnYK2t3BWwURBPs3dRR/cki/XW/ke9jMR6OrBstf6GdNRZuETBvFCqhWFRXqqhQVQ0z5wYh0u1m8Hve2GeDTN09U5GqHBAdr6fWYJ9kcxFpYcjHqmy2bWfcsIP0QnzBb5V+Rj4d1+RfSbqu2WwYheM2SpMYLfD/gNcw91uyah0R+QK1TeoaXzg0QHVbWa63KXc9YnjNW1uNvu/0ivBHRLIMKSDWcL3kAIBREiCgA2Cst3we9KLJe/IPhVvW7P5hZkblMQ8Mf/bpW5BH1BjHEY2Ul1QiQXZ3MHDetgIy3ZEuJhp7sbddwxGvZ2LVhGCpoy6TbWKSDcKOQzzTitULNXAkjBktjFFF+OkgMxnJXa4+tFKhB1Mik51Rv3COZ+Z1X3IhOMkUYQnJ1VJugJPypuNF8YNuNu4=
    - secure: NJjPGOdBnuZSslWiwu9jy0YJoM7rUcT+aNt+rpS+yV3Lgx/EEhhM6iWuL5D7PZWNKpygAXxYZe1LxC66jswMqHcp2/H6NRkevMGvkaU2o/rXtYKZxWue4Fls6w/sa1gWWvO+RofXeJO1YxYHvAY+NPdfUiFoard2Eu8EPJAtSeq0TzjZ2LFzzhTefvVj1f4CCsJgUqvWuzF1BcVDBJzrm1vWya8GNeV9yxVSjpuDFAEl8Mg0OD+syBaeGAceHSpPPvbxPSRiJnfE6e4ayGBjywj4QGg4Xrh0vAI0xC9oXqofmrVUNdxUTdtrRJkC2iHT1M8zgMiZTRy9/8UjHhYoKLMZCrh9Aw5pjGdp2Qf49Qsa2i0ZwwlSk5yc0HE3rF1cikhJASLt87MKNod6JztyHfIrj2flik03oN/7vtNN0/LVnzPsfXerNmRVnTaCD+8WNofAo1GeTsxOU/ESvhwIeTt5aUkoYUd2IePkoyM89YKoaUoGTbHkeQDqXhHJTLT6CIuUu+ndjfW3ZJrP2eLMDnf5JbdS+kClCjK/ji0VBNGG/tn02c6c/Pr4CSBRvNn+/p4hyjTd655SPhFoaCZba+n+uBNmzL0VHMivKqCMbEKQiPFIGZkKhvuomnqtkdy3mD+4xpQwH7kkQFB4b79yMPVtNJ/w+Twmo1316+s6gk8=
